app = "etf-screener-gateway"
primary_region = "iad"

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[http_service.checks]]
  interval = "15s"
  grace_period = "5s"
  method = "GET"
  path = "/health"
  protocol = "http"
  timeout = "10s"
  tls_skip_verify = false

[env]
  NGINX_WORKER_PROCESSES = "auto"
  NGINX_WORKER_CONNECTIONS = "1024"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256